### ISSUE TITLE
get maven tf

### ISSUE THREAD

**Issue by shedaniel** [minecraft-cursed-legacy/Plasma#36]

**Comment by shedaniel** [comment]
when add this is annoying

**Comment by Devan-Kerman** [comment]
use a gh repo as a maven

**Comment by valoeghese** [comment]
ok I assigned some people that would be veri good at this job

**Comment by Devan-Kerman** [comment]
wait no ⚪

**Comment by ramidzkh** [comment]
wait im good at this job

**Comment by ramidzkh** [comment]
where do i send a job application

**Comment by Devan-Kerman** [comment]
ur hired and im ur manager

**Comment by Devan-Kerman** [comment]
outsorcing

**Comment by hYdos** [comment]
and im yours

**Comment by Devan-Kerman** [comment]
no

**Comment by jearmstrong21** [comment]
yes

**Comment by CoolMineman** [comment]
Use [this](https://github.com/features/packages) and setup auto compile k thx

**Comment by jearmstrong21** [comment]
:irritatered:

**Comment by shedaniel** [comment]
it takes 2 seconds to set up jibtray

**Comment by hYdos** [comment]
it takes 2 seconds to give me mcp king ++ :tiny_potato:

**Comment by CoolMineman** [comment]
@hYdos open a new issue

**Comment by hYdos** [comment]
but thats issue spam yes

**Comment by CoolMineman** [comment]
If it's not important enough for an issue it's not important enough to do

**Comment by valoeghese** [comment]
this is outdated. we use halfmaven now
