### ISSUE TITLE
method_2171() -> tick?

### ISSUE THREAD

**Issue by valoeghese** [minecraft-cursed-legacy/Plasma#43]

**Comment by valoeghese** [comment]
![image](https://user-images.githubusercontent.com/46117728/83699733-f9699300-a658-11ea-9d92-22dfe33e2573.png)
![image](https://user-images.githubusercontent.com/46117728/83699748-038b9180-a659-11ea-9a98-c8f73b38aca7.png)

**Comment by CoolMineman** [comment]
ARR and yes

**Comment by valoeghese** [comment]
addressed in my next pr.
